/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_kuaikuaiyu_assistant_utils_JniUtil */

#ifndef _Included_com_kuaikuaiyu_assistant_utils_JniUtil
#define _Included_com_kuaikuaiyu_assistant_utils_JniUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_kuaikuaiyu_assistant_utils_JniUtil
 * Method:    getSignKey
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_kuaikuaiyu_assistant_utils_JniUtil_getSignKey
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
