/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_kuaikuaiyu_assistant_utils_JniUtil */
#include "hmacs256.h"
#ifndef _Included_com_kuaikuaiyu_assistant_utils_JniUtil
#define _Included_com_kuaikuaiyu_assistant_utils_JniUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_kuaikuaiyu_assistant_utils_JniUtil
 * Method:    sign
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_kuaikuaiyu_assistant_utils_JniUtil_sign
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
